/** Social platforms — icon + name for admin dropdowns */
export const SOCIAL_PLATFORMS = [
  { name: 'Instagram', icon: '📸' },
  { name: 'Facebook', icon: '👤' },
  { name: 'YouTube', icon: '▶️' },
  { name: 'TikTok', icon: '🎵' },
  { name: 'Twitter', icon: '🐦' },
  { name: 'Telegram', icon: '✈️' },
  { name: 'WhatsApp', icon: '💬' },
  { name: 'Snapchat', icon: '👻' },
  { name: 'LinkedIn', icon: '💼' },
  { name: 'Pinterest', icon: '📌' },
  { name: 'Spotify', icon: '🎧' },
  { name: 'Threads', icon: '🧵' },
  { name: 'Discord', icon: '🎮' },
  { name: 'Twitch', icon: '🟣' },
  { name: 'Reddit', icon: '🔴' },
  { name: 'Other', icon: '🌐' },
];

export const SOCIAL_ICONS = [
  { icon: '📸', label: 'Instagram' },
  { icon: '👤', label: 'Facebook' },
  { icon: '▶️', label: 'YouTube' },
  { icon: '🎵', label: 'TikTok' },
  { icon: '🐦', label: 'Twitter' },
  { icon: '✈️', label: 'Telegram' },
  { icon: '💬', label: 'WhatsApp' },
  { icon: '👻', label: 'Snapchat' },
  { icon: '💼', label: 'LinkedIn' },
  { icon: '📌', label: 'Pinterest' },
  { icon: '🎧', label: 'Spotify' },
  { icon: '🧵', label: 'Threads' },
  { icon: '🎮', label: 'Discord' },
  { icon: '🟣', label: 'Twitch' },
  { icon: '🔴', label: 'Reddit' },
  { icon: '⚡', label: 'Boost' },
  { icon: '🌐', label: 'Other' },
  { icon: '📱', label: 'Mobile' },
];
